variables:
  DOCKER_TLS_CERTDIR: "/certs"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  JAVA_OPTS: "-Duser.timezone=UTC"

cache:
  key: $CI_JOB_NAME
  paths:
    - .m2/repository/

stages:
  - build
  - deploy

build-gradle:
  stage: build
  image: gradle:7.3.3-jdk17
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/
  script:
    - chmod +x ./gradlew
    - ./gradlew --build-cache --gradle-user-home cache/ check -x test
    - gradle build -x test
  artifacts:
    name: "pumps-server"
    expire_in: 15 min
    paths:
      - build/libs/*-SNAPSHOT.jar

trigger-deploy-pipeline:
  stage: deploy
  trigger:
    include:
      - local: .gitlab/pipelines/pipeline-snapshot.yaml
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
