variables:
  DOCKER_TLS_CERTDIR: "/certs"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  JAVA_OPTS: "-Duser.timezone=UTC"

cache:
  key: $CI_JOB_NAME
  paths:
    - .m2/repository/

stages:
  - build
  - deploy

build-gradle:
  stage: build
  image: gradle:7.3.3-jdk17
  script:
    - gradle build
  artifacts:
    name: "pumps-server"
    expire_in: 15 min
    paths:
      - target/*.jar

trigger-deploy-pipeline:
  stage: deploy
  trigger:
    include:
      - local: .gitlab/pipelines/pipeline-snapshot.yaml
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
