version: '3'
services:

  pumps-server:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ${IMAGES_PATH}:/mnt/images
    depends_on:
      - db

  db:
    image: postgis/postgis:14-master
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pumps
      POSTGRES_USER: pumper
      POSTGRES_PASSWORD: pumPern1ckel
    container_name: pumps-postgresql-docker
    volumes:
      - /home/joerg/pgdata:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.de
      PGADMIN_DEFAULT_PASSWORD: geheim
    ports:
      - "81:80"
